{
    'name':'School Management',
    'application':True,
    'version': '18.0.1.0.0',
    'author': "Alan John",
    'category': 'Education',
    'summary': 'THIS IS UPDATED',
    'depends': ['mail','base','sale_management','contacts','base_automation'],
    'data': [
        'data/sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/mail_template_data.xml',
        'data/base_automation_data.xml',
        'security/res.groups.xml',
        'security/ir.model.access.csv',
        'security/ir.rule.xml',
        'views/sale_order_state_views.xml',
        'views/school_student_views.xml',
        'views/school_department_view.xml',
        'views/school_class_view.xml',
        'views/school_subject_view.xml',
        'views/school_academic_year_view.xml',
        'views/school_club_view.xml',
        'views/school_event_view.xml',
        'views/school_teacher_view.xml',
        'views/school_leave_views.xml',
        'views/school_exam_views.xml',
        'views/school_papers_views.xml',
        'views/school_menu_list.xml',
    ],
}
# -*- coding: utf-8 -*-

